name: 'Google Cloud Platform (GCP) CLI - covertbert'
description: 'GitHub Action with all the components of the Google Cloud SDK, including beta components'
author: 'Bertie Blackman <blackmanrgh@gmail.com>'
branding:
  icon: 'cloud'
  color: 'blue'
inputs:
  PROJECT_ID:
    description: 'Project id'
    required: true
  APPLICATION_CREDENTIALS:
    description: 'GCP authorization credentials'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
